// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMNVPLf9xfEmqawxpuGPyQ4ClYsdCCOGk',
    appId: '1:661746596550:web:15523b4b3ef8f99b3f35c7',
    messagingSenderId: '661746596550',
    projectId: 'aurb-76255',
    authDomain: 'aurb-76255.firebaseapp.com',
    storageBucket: 'aurb-76255.appspot.com',
    measurementId: 'G-PTXRESRLPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtsdh9et5i1_VTuShmwvUy2ediuSituU4',
    appId: '1:661746596550:android:82907f6a00fd632c3f35c7',
    messagingSenderId: '661746596550',
    projectId: 'aurb-76255',
    storageBucket: 'aurb-76255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvsUyvqaxqr-3mlt9ZBP9PLuH8f80bPC0',
    appId: '1:661746596550:ios:6aac899dfb251b513f35c7',
    messagingSenderId: '661746596550',
    projectId: 'aurb-76255',
    storageBucket: 'aurb-76255.appspot.com',
    iosClientId: '661746596550-uquqq8lgc29o4llq26dsuuau65cn26p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvsUyvqaxqr-3mlt9ZBP9PLuH8f80bPC0',
    appId: '1:661746596550:ios:a6aa0c8ae4e318ea3f35c7',
    messagingSenderId: '661746596550',
    projectId: 'aurb-76255',
    storageBucket: 'aurb-76255.appspot.com',
    iosClientId: '661746596550-u88cnqjmntkp1tb5kpg8ever47ir0aip.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurb.RunnerTests',
  );
}
